# Generated by Django 5.1.4 on 2025-05-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('ایران', 'ایران')], default='Iran', max_length=100, verbose_name='Ülke'),
        ),
    ]
