# Generated by Django 5.1.4 on 2025-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جزئیات آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('ایران', 'ایران')], default='Iran', max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_corporate',
            field=models.BooleanField(default=False, verbose_name='آیا شرکتی است؟'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='تهران', max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه مالیاتی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tax_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اداره مالیاتی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='شماره تلفن'),
        ),
    ]
