# Generated by Django 5.1.4 on 2025-05-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_apartment_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کد های تایید'},
        ),
    ]
