# Generated by Django 5.1.4 on 2025-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_options_alter_code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Iran', 'ایران')], default='Iran', max_length=100, verbose_name='کشور'),
        ),
    ]
