# Generated by Django 5.1.4 on 2025-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100, unique=True, verbose_name='Sipariş Numarası')),
                ('log', models.CharField(blank=True, max_length=250, null=True, verbose_name='Detay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
