# Generated by Django 5.1.4 on 2025-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'verbose_name': 'گزارش پرداخت', 'verbose_name_plural': 'گزارشات پرداخت'},
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='log',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='orderId',
            field=models.CharField(max_length=100, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
