# Generated by Django 5.1.4 on 2025-05-17 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('users', '0004_alter_address_options_alter_code_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'مقدار ویژگی', 'verbose_name_plural': 'مقادیر ویژگی'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم\u200cهای سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='commentmedia',
            options={'verbose_name': 'رسانه نظر', 'verbose_name_plural': 'رسانه\u200cهای نظر'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'جزئیات محصول', 'verbose_name_plural': 'جزئیات محصول'},
        ),
        migrations.AlterModelOptions(
            name='productdetailmedia',
            options={'verbose_name': 'رسانه جزئیات محصول', 'verbose_name_plural': 'رسانه جزئیات محصول'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'verbose_name': 'رسانه محصول', 'verbose_name_plural': 'رسانه\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='relatedproduct',
            options={'verbose_name': 'محصول مرتبط', 'verbose_name_plural': 'محصولات مرتبط'},
        ),
        migrations.AlterModelOptions(
            name='shippingcarrier',
            options={'verbose_name': 'پیک ارسال', 'verbose_name_plural': 'پیک\u200cهای ارسال'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'لیست علاقه\u200cمندی', 'verbose_name_plural': 'لیست\u200cهای علاقه\u200cمندی'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('attributes', 'ویژگی\u200cها'), ('variants', 'محصولات مرتبط')], default='attributes', max_length=10, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات ویژگی'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='key',
            field=models.CharField(max_length=100, verbose_name='کلید ویژگی'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, default='brands/defaults/default_banner.webp', upload_to='brands/banner', verbose_name='تصویر بنر برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='brands/defaults/default_logo.webp', upload_to='brands/logo', verbose_name='لوگو برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.comment', verbose_name='پاسخ به'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (۰–۵)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.comment', verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='commentmedia',
            name='image',
            field=models.ImageField(upload_to='comment_media/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل تخمینی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.shippingcarrier', verbose_name='پیک انتخاب\u200cشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'سفارش ثبت شد'), ('paid', 'پرداخت انجام شد'), ('payment_failed', 'پرداخت ناموفق'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل داده شد'), ('canceled', 'لغو شد')], default='pending', max_length=15, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رهگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='shop.attributevalue', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف\u200cخورده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.product', verbose_name='محصول والد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (۰–۵)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه انبار (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_detail_media/', verbose_name='فایل رسانه'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='media_position',
            field=models.CharField(choices=[('center', 'وسط'), ('left', 'چپ'), ('right', 'راست')], default='center', max_length=10, verbose_name='موقعیت رسانه'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], default='image', max_length=5, verbose_name='نوع رسانه'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productdetailmedia',
            name='productDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.productdetail', verbose_name='جزئیات محصول'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='product_media/', verbose_name='فایل رسانه'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], default='image', max_length=5, verbose_name='نوع رسانه'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='normal_size',
            field=models.ImageField(blank=True, null=True, upload_to='product_media/', verbose_name='سایز معمول'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_media/', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='shop.product', verbose_name='محصول مبدا'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='related_type',
            field=models.CharField(choices=[('similarity', 'مشابه'), ('buy-together', 'خرید با هم')], default='similarity', max_length=20, verbose_name='نوع مرتبط\u200cسازی'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='shop.product', verbose_name='محصول مقصد'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='logo',
            field=models.ImageField(blank=True, help_text='اختیاری: لوگوی پیک برای نمایش در فرانت\u200cاند', null=True, upload_to='shipping_carriers/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام پیک'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='قالب لینک رهگیری'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='shop.product', verbose_name='محصولات موردعلاقه'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
